import type { NextPage } from "next";
import Head from "next/head";
import AboutMe from "../components/aboutme";
import Masthead from "../components/masthead";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Trung&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Masthead />
      <AboutMe />
    </div>
  );
};

export default Home;
